// Package main provides the copilot-runner binary that uses the Copilot SDK
// for programmatic agent control.
package main

import (
	"encoding/json"
	"fmt"
	"os"
)

// Config represents the runner configuration loaded from a JSON file.
// This structure is generated by the Copilot SDK engine during workflow compilation
// and contains all parameters needed to create a Copilot SDK session.
type Config struct {
	// CLIPath is the path to the Copilot CLI binary (required by the SDK)
	CLIPath string `json:"cli_path"`

	// GithubToken is the GitHub token for authentication (can also come from env)
	GithubToken string `json:"github_token,omitempty"`

	// Model is the model to use for the session
	Model string `json:"model,omitempty"`

	// WorkingDirectory is the working directory for tool operations
	WorkingDirectory string `json:"working_directory,omitempty"`

	// LogLevel for the CLI server process
	LogLevel string `json:"log_level,omitempty"`

	// LogDir is the directory for writing log files
	LogDir string `json:"log_dir,omitempty"`

	// PromptFile is the path to the file containing the prompt text
	PromptFile string `json:"prompt_file"`

	// AvailableTools is a list of tool names to allow.
	// When specified, only these tools will be available.
	// A nil/empty value means all tools are available.
	AvailableTools []string `json:"available_tools,omitempty"`

	// ExcludedTools is a list of tool names to disable.
	// Ignored if AvailableTools is specified.
	ExcludedTools []string `json:"excluded_tools,omitempty"`

	// MCPConfigPath is the path to the MCP server configuration file
	MCPConfigPath string `json:"mcp_config_path,omitempty"`

	// Streaming enables streaming of assistant message chunks
	Streaming bool `json:"streaming"`

	// Timeout in seconds for the session (0 = default)
	Timeout int `json:"timeout,omitempty"`

	// MetricsFile is the path to write metrics JSON output
	MetricsFile string `json:"metrics_file,omitempty"`

	// Env contains additional environment variables
	Env map[string]string `json:"env,omitempty"`
}

// LoadConfig reads and parses a runner configuration from a JSON file.
func LoadConfig(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read config file %s: %w", path, err)
	}

	// Expand environment variables in the config
	expanded := os.ExpandEnv(string(data))

	var config Config
	if err := json.Unmarshal([]byte(expanded), &config); err != nil {
		return nil, fmt.Errorf("failed to parse config file %s: %w", path, err)
	}

	// Apply defaults
	if config.CLIPath == "" {
		config.CLIPath = "copilot"
	}
	if config.LogLevel == "" {
		config.LogLevel = "info"
	}

	// Get GitHub token from environment if not in config
	if config.GithubToken == "" {
		config.GithubToken = os.Getenv("COPILOT_GITHUB_TOKEN")
	}

	return &config, nil
}
