// copilot-runner is a binary that uses the GitHub Copilot SDK (Go) to
// programmatically control a Copilot agent session.
//
// It reads configuration from a JSON file (generated by the gh-aw compiler's
// copilot-sdk engine), creates a Copilot SDK client, establishes a session,
// sends the prompt, and collects metrics.
//
// Usage:
//
//	copilot-runner --config /path/to/config.json
//
// The config file contains model, tools, MCP servers, and other session
// parameters. See cmd/copilot-runner/config.go for the full schema.
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"os/signal"
	"syscall"
)

func main() {
	configPath := flag.String("config", "", "Path to the runner configuration JSON file")
	flag.Parse()

	if *configPath == "" {
		fmt.Fprintf(os.Stderr, "Error: --config flag is required\n")
		fmt.Fprintf(os.Stderr, "Usage: copilot-runner --config /path/to/config.json\n")
		os.Exit(1)
	}

	// Load configuration
	config, err := LoadConfig(*configPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error loading config: %v\n", err)
		os.Exit(1)
	}

	// Create context with signal handling
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		sig := <-sigCh
		fmt.Fprintf(os.Stderr, "\nReceived signal %v, shutting down...\n", sig)
		cancel()
	}()

	// Create and run the runner
	runner := NewRunner(config)
	if err := runner.Run(ctx); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}
